spring.application.name: rest-with-spring-boot-and-java-erudio
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: false
   # properties:
   #   hibernate:
   #     dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
